### ISSUE TITLE
请问是否支持从外部浏览器唤起 tokenPocket后在dapp浏览器打开页面

### ISSUE THREAD

**Issue by mylonelyplanet** [TP-Lab/TokenPocket-Protocol#1]
类似imtoken：imtokenv2://navigate?screen=DappView&url=https://token.im
or
类似trust: https://link.trustwallet.com/open_url?coin_id=60&url=https://compound.finance

**Comment by chendatony31** [comment]
@mylonelyplanet  支持的 看下这里 https://github.com/TP-Lab/TokenPocket-Protocol#dapp-%E6%B5%8F%E8%A7%88%E5%99%A8%E6%89%93%E5%BC%80url--call-tokenpocket-to-open-url-with-dapp-browser

**Comment by hongri-xiao** [comment]
请问如何获取某两个币的实时交易价格呢?
