### ISSUE TITLE
ios只能拉起app，无法跳转到dapp浏览器打开dapp

### ISSUE THREAD

**Issue by 2697a** [TP-Lab/TokenPocket-Protocol#4]

**Comment by justXyS** [comment]
跳转的url发一下

**Comment by 2697a** [comment]
好的
tpdapp://open?params={'url': 'https://dapp.cybers.coinbasis.us/Coinbasis/#/','chain': 'BSC','source': 'Coinbasis'}
android是可以正常打开dapp的

**Comment by justXyS** [comment]
链接需要URL encode一下

**Comment by 2697a** [comment]
我是用vue写的，encodeURI("tpdapp://open?params={'url': 'https://dapp.cybers.coinbasis.us/Coinbasis/#/','chain': 'BSC','source': 'Coinbasis'}")和(encodeURIComponent("tpdapp://open?params={'url': 'https://dapp.cybers.coinbasis.us/Coinbasis/#/','chain': 'BSC','source': 'Coinbasis'}")好像都不可以正常打开

**Comment by 2697a** [comment]
只encode params也不行

**Comment by justXyS** [comment]
{'url': 'https://dapp.cybers.coinbasis.us/Coinbasis/#/','chain': 'BSC','source': 'Coinbasis'} 这部分json的语法需要用双引号
